image: docker:latest

cache:
  paths:
  - .cache/

services:
- docker:dind

stages:
- build

build:
  stage: build
  script:
  - ${CI_PROJECT_DIR}/.docker/build.sh
  - ${CI_PROJECT_DIR}/.docker/deploy.sh
