image: docker:latest

cache:
  paths:
  - .cache/

services:
- docker:dind

stages:
- build
- publish

build:
  stage: build
  script:
  - ${CI_PROJECT_DIR}/.docker/build.sh

publish:
  stage: publish
  script:
  - ${CI_PROJECT_DIR}/.docker/deploy.sh
